### ISSUE TITLE
Updates to Major List (2022-2023 Term 1)

### ISSUE THREAD

**Issue by ansonscleung** [LCM288/cuhkacs-online#1]
## TLDR
Update Major List as of 2022-2023 Term 1

## Background
As William the "Toxic L God" stated, changes have been made to Lists of Majors

## Short-term solution
Update `src\static\major.json` according to [RES Program Codes](http://www.res.cuhk.edu.hk/zh-tw/general-information/program-codes)

## Long-term solution
Update automatically/fetch programme codes and lists according to any CUHK APIs or crawl from CUHK websites

**Comment by LCM288** [comment]
oh you right, should find the script

**Comment by ansonscleung** [comment]
## Further Studies on data sources
### [RES](http://www.res.cuhk.edu.hk/zh-tw/general-information/program-codes)
+ve:
- Contains most programmes

-ve:
- Hard-coded HTML
### [Undergraduate Admissions](http://admission.cuhk.edu.hk/programme-list.html)
+ve:
- [JSON-formatted data source!](http://[admission.cuhk.edu.hk/assets/js/data.js?20211126](http://admission.cuhk.edu.hk/assets/js/data.js?20211126))
- Contains the latest info on Faculties and Programmes

-ve:
- Only programmes with active admission

**Comment by ansonscleung** [comment]
After studying data sources:
![image](https://user-images.githubusercontent.com/3136002/186917653-3f2a4635-d446-4625-bac5-ba0871c5cff2.png)
